FROM prom/prometheus:latest

WORKDIR  /prometheus

COPY config/prometheus.yml /prometheus/prometheus.yml

EXPOSE 9090

CMD ["--config.file=/prometheus/prometheus.yml", "--web.external-url=https://e3r8p4.1337.ma/prometheus", "--web.route-prefix=/"]